name: Build binaries

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container: devkitpro/devkitppc
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: make
      - name: Package
        run: |
          mkdir -p apps/Mail-Patcher/
          cp Mail-Patcher.dol apps/Mail-Patcher/boot.dol
          cp icon.png apps/Mail-Patcher/icon.png
          cp meta.xml apps/Mail-Patcher/meta.xml
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with: 
          name: Mail-Patcher
          path: apps
